### ISSUE TITLE
The screensaver doesn't seem to work with Mojave

### ISSUE THREAD

**Issue by zzzDavid** [nemesit/SwiftBubble#10]
When I try to set it as the screensaver the preview shows a message that it is incompatible with Mojave. I have been using this screensaver for months and it's splendid. Please update this screensaver if you find time. Thank you for creating such a beautiful screensaver.

**Comment by zntfdr** [comment]
Hi @zzzDavid, I've raised the issue before (#9), and @nemesit fixed it right away! 
Just download the [latest version](https://github.com/nemesit/SwiftBubble/releases) and everything will be fine 🙂

**Comment by zzzDavid** [comment]
Thank you!
