### ISSUE TITLE
Can't work in Mojave (10.14)

### ISSUE THREAD

**Issue by nicing** [nemesit/SwiftBubble#11]
I just upgrade my system, it show this message: 
You cannot use the SwiftBubble screen saver with this version of macOS.

**Comment by zntfdr** [comment]
It's been fixed already, please see issue #9 and #10.

@nemesit I suggest you to write something in the main readme, or people will keep opening these kind of issues.

**Comment by nicing** [comment]
@zntfdr Thanks a lot!
