### ISSUE TITLE
Support for Catalina(10.15)

### ISSUE THREAD

**Issue by nicing** [nemesit/SwiftBubble#12]
Hi @nemesit, I upgraded my macOS to Catalina(10.15), the screensaver doesn't work in the new system, any plan to update the screensaver?

Thanks!

**Comment by xue9835426** [comment]
same problem.

**Comment by zzzDavid** [comment]
Hi guys, I updated this screen saver for Big Sur, check it out here: https://github.com/zzzDavid/bubble-screensaver
