### ISSUE TITLE
Not working, now - animated SVG help

### ISSUE THREAD

**Issue by ColinLondon** [nemesit/SwiftBubble#13]
Absolutely love this. But no longer working on Mojave+ I think.

Apparently, Photoshop did the heavy lifting. I'd love to turn this into an animated SVG using After Effects and Lottie. But I am no techie. Anyway I can do that? Or maybe get my hands on the Photoshop and take it from there?

I think this would be a stunning HTML5 animation.

Sorry for being cheeky and thanks in advance to those that can help.

**Comment by LeeBinder** [comment]
https://github.com/zzzDavid/bubble-screensaver 👍

**Comment by nemesit** [comment]
sry its basically bitmap images, no way to make it an svg without recreating everything from scratch. but if you do let me know ;-p
