### ISSUE TITLE
Love this, can it support 5K Retina Display maybe?

### ISSUE THREAD

**Issue by hzlzh** [nemesit/SwiftBubble#2]
Checkout this screenshot
<img width="2560" alt="screen shot 2015-08-23 at 3 30 54 pm" src="https://cloud.githubusercontent.com/assets/1049575/9427351/fa68e508-49ab-11e5-85de-e7360a346c8c.png">

**Comment by nemesit** [comment]
upscaling it even further might be a bit challenging but I'll try when I find the time to

**Comment by nemesit** [comment]
not sure whether the new update fixes your issue  but please report back if it does/does not xD

**Comment by tellok** [comment]
yeah, hungry for a higher resolation one.

**Comment by nemesit** [comment]
@hzlzh did you try the updated version?

**Comment by hzlzh** [comment]
> @hzlzh did you try the updated version?

I tired, nothing but black
<img width="232" alt="image" src="https://user-images.githubusercontent.com/1049575/155123180-d8eb94cd-0a4d-433c-ab8b-ccf2f70c7859.png">

<img width="593" alt="image" src="https://user-images.githubusercontent.com/1049575/155123059-70f3a787-0a70-46d7-9ff3-2bbcfcca7aaa.png">

**Comment by nemesit** [comment]
published a new release might work now, although I didn't test it on intel yet.
Might also take a while to start up, not yet sure why.

**Comment by hzlzh** [comment]
This new release version should be fixed, especially for M1 Macbooks. pls
have a try.
