### ISSUE TITLE
Not compatible with 10.10.5+ need to be rebuilt.

### ISSUE THREAD

**Issue by sermelipharo** [nemesit/SwiftBubble#3]
Can't set it as screensaver, OS X displays something like "app need to be updated to be compatible with this version of OS"

**Comment by nemesit** [comment]
sry I do not support outdated insecure OS versions, but you can add it yourself and send a pull request :-)

**Comment by sermelipharo** [comment]
So will it be supported by el capitan?

> insecure

Yosemite still receiving security updates as El Capitan

**Comment by nemesit** [comment]
I'll upload a new version tomorrow (currently on cellular)

> Yosemite still receiving security updates as El Capitan  

sometimes apple likes to not fix issues for the previous version (although I admit that I read 10.5+ xD)  
I don't have an SDK < 10.11 installed though (again cellular is the problem xD), it should be easy to simply change the target sdk in the new version which might also run a bit smoother.

**Comment by nemesit** [comment]
I updated the screen saver so it should now run on el capitan and maybe previous versions, else a simple recompile with a lower sdk should be enough

**Comment by sermelipharo** [comment]
thank you, will try it later today (GMT+3) from my home mac

**Comment by sermelipharo** [comment]
works fine now. but shouldn't bubble be moving across the screen? currently it just plays animation at centre of the screen

**Comment by nemesit** [comment]
nope thats another screen saver for which I haven't found a way to replicate it yet
