### ISSUE TITLE
Display Off not working..

### ISSUE THREAD

**Issue by DesignerWhere** [nemesit/SwiftBubble#4]
When using this screen saver, the display off function isn't working. Changed to a different screen saver and the display (which is set to test at 1 minute) switches off. Leave it on the bubbles and it doesn't.

**Comment by nemesit** [comment]
yeah thats a problem that originates in the usage of avplayer which prevents display sleep, will fix it when I got time :-)

**Comment by speakerz** [comment]
Same problem here. Thanks for the great work.

**Comment by j0shyua** [comment]
Will this ever be fixed? It's just a small problem that doesn't really matter, but I'm just afraid i'll accidentally leave my MacBook open and forget it's still on.

**Comment by nemesit** [comment]
yeah it'll get fixed eventually, just don't have much time at the moment

**Comment by nemesit** [comment]
This should now be fixed, let me know if something does not work :-)
