### ISSUE TITLE
Screen Saver Preferences freezing 

### ISSUE THREAD

**Issue by suntrop** [nemesit/SwiftBubble#5]
When I click the Desktop & Screen Saver icon and change to the Screen Saver tab the System Preferences freezes. I tried multiple times and noticed when I click fast enough on another screen saver sys. pref will work again. Using 10.10.1

BTW … looks really cool! First screen saver after years of Flurry :-D
Would be nice if monitor shuts down and even cooler are settings for thickness or speed :-)

**Comment by nemesit** [comment]
should be fixed in big sur
