### ISSUE TITLE
Screensaver may cause abnormal display on DELL U2417 monitor

### ISSUE THREAD

**Issue by spencerwooo** [nemesit/SwiftBubble#7]
# Problem
When I try to wake my MacBook up after the screensaver is up, my monitor may temporarily show a flickering abnormal display --- a flashing all-white (or some other color) screen. The flashing won't stop until I unplug my monitor and plug it on again. 

# Hardware information:
- MacBook (Retina, 12-inch, Early 2016)
- DELL U2417H (Monitor)

# Software information:
- macOS High Sierra 10.13

# ALSO
This screensaver is AWESOME!!! I LOVE IT!!!

**Comment by nemesit** [comment]
does that happen with other screensavers too or just this one?

**Comment by spencerwoo98** [comment]
Nope, just this one. I also use Fliqlo and other third party screensavers but only this one has this problem.
![screensaversettings](https://user-images.githubusercontent.com/32114380/32610638-56874eb8-c59e-11e7-9710-b50c81f522d3.jpg)

**Comment by nemesit** [comment]
does it happen with the latest version?

**Comment by spencerwooo** [comment]
wow, three years later, and I don't use a Mac (or a Dell U2417) anymore ... let me verify this with my friend later
