### ISSUE TITLE
Mojave Support 

### ISSUE THREAD

**Issue by zntfdr** [nemesit/SwiftBubble#9]
Just upgraded to Mojave and the current screensaver version apparently is not compatible 😅, you can see the same issue in another repo here: https://github.com/JohnCoates/Aerial/issues/464

**Comment by nemesit** [comment]
I‘ll try to update it later today/tomorrow, I also found a few ways to enhance the graphics a bit (hopefully xD)

**Comment by zntfdr** [comment]
>I‘ll try to update it later today/tomorrow, I also found a few ways to enhance the graphics a bit (hopefully xD)

@nemesit awesome, thank you very much 🙌🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nemesit** [comment]
should run on Mojave now

**Comment by zntfdr** [comment]
Just tried, it works 🎉

Many thanks 😊
